language: node_js
node_js:
- '8'
- '10'
cache: yarn
script: yarn ci
deploy:
  skip_cleanup: true
  provider: npm
  email: igor@kamyshev.me
  api_key:
    secure: nW/QRr4Fuq3FJtrhQHV0qd+w7WggqPdJv5V47ULCDdjk/02B/O3wpLCHdInn36gmaWVc9fpcuh3cw4fZGIxAd4D14Pj1P/K2+9lnmsicjkltKQkislg6EnWGHz8A7MrNpLzEATpB3WBoEiN5Yo/UJK8zP7AzWmw0s2slFO2nWdysSiMswasShG1CEXCc3RvQjtcUmYK3sYJgVntJ+iLNKuqTSaRVHJSB7cV0ETcXbDRkeGH1TcZyWdtJQRdLNyyXJ4Ak6vMLNDJrn7H2DGQRc8qsvLiqE85HITO1lgDoEHLux8vdPBp6Z3QpuGDhfxDrCGj96kEc6+QVvN5s2LEMrRtl2Ov49B5xKTPC9oK1JOrzskztndk6e1q/1UDLF0rFpCxTvibDV+KC7IGh8DNTaK49DV2NbNlFKOX78RiqOF9980AgzFbxBWAUCq6/6FKvwaLiFjE1isaxcQvxScW6elAQ3h+INHdxuE2AtrveJXQVRgmobKg8BwxqeTGHN4TebuuFOcKGjikS8dTvjYhOBcNCJxeARQKTzVw/FxD5Sb9wHFA8gs/WVTB6Hk7LJEmnooSD6GoikZWxQiv27aculz2/dKyXNE/E+BmHcUU0A60eQy6BNmOmWr9PVqIW75Te19pirgiWYdjrd8TMFJLdzOR+zqPs5rY1XZVSZ6tnrGA=
  on:
    tags: true
    repo: solid-soda/config
